name: envtest
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6,<3.10
  - pip
  - contourpy           1.1.1
  - cycler              0.12.1
  - envtest             0.1.dev3+gbe99846 /Users/yw3523/environments_mpm
  - fonttools           4.43.1
  - importlib-resources 6.1.0
  - kiwisolver          1.4.5
  - matplotlib          3.8.0
  - mpmath              1.3.0
  - numpy               1.26.0
  - packaging           23.2
  - Pillow              10.0.1
  - pip                 23.2.1
  - pyparsing           3.1.1
  - python-dateutil     2.8.2
  - scipy               1.11.3
  - setuptools          68.0.0
  - six                 1.16.0
  - sympy               1.12
  - wheel               0.41.2
  - zipp                3.17.0